### ISSUE TITLE
关于在[-interval,interval]区间梯度截断的两个问题

### ISSUE THREAD

**Issue by CaT-Hode** [DravenALG/ReSTE#2]
1. 首先代码为何要分成两段截断?
```python
tmp[(input <= interval) & (input >= 0)] = approximate_function(interval, o) / interval
tmp[(input <= 0) & (input >= -interval)] = -approximate_function(-interval, o) / interval
```
这两段的赋值结果似乎是相同的

2. 其次为何不直接将interval带入到`(1 / o) * math.pow(interval, (1 - o) / o)`之中,
而是`approximate_function(interval,o)/interval`,
等效为`math.pow(interval, (1 - o) / o)`
这样截断区间的值会和非截断区存在`o`倍的差距, 导致导数不连续, 这样做的目的是什么呢?

个人认为的一种简洁的实现方法:
```python
class BinaryQuantize_ReSTE(Function):
    @staticmethod
    def forward(ctx, input, o):
        ctx.save_for_backward(input,o)
        out = torch.sign(input)
        # out[out==0] = 1
        return out

    @staticmethod
    def backward(ctx, grad_output):
        input,o = ctx.saved_tensors
        grad_max = math.pow(0.1, (1-o)/o) / o
        input_abs = torch.abs(input)
        grad_input = torch.pow(input_abs, (1-o)/o).clamp(max = grad_max)
        grad_input[input_abs>1.5] = 0
        grad_input *= grad_output
        return grad_input, None
```

**Comment by DravenALG** [comment]
1. 由于ReSTE是关于原点对称的，所以确实两部分的梯度确实是一样的。

2. 因为ReSTE的形式会令接近0的部份梯度趋近于无穷大，所以我们对于这一部分使用了简单的线性函数来替代（这可以有对应的前向过程的曲线，因此在拟合误差和梯度稳定性的分析上也是可以说得通的），正文章节3.3的最后也有所阐述。

3. 关于你的代码，没理解错的话大致的逻辑是采用ReSTE的0.1的点的梯度来替换这部分，这样的话很难直接抽象出对应的前向过程，也没办法进行拟合误差和梯度稳定性的分析，不过我在完成这个工作的时候确实没有考虑过这样的做法，你可以尝试一下，进一步跑一下实验，效果不错或者你有什么见解可以跟我讨论。
